#!/bin/sh
### BEGIN INIT INFO
# Provides:          pp-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

#
# see this for above info:
# http://danilodellaquila.com/blog/how-to-install-lotus-domino-8.5-on-ubuntu-part-ii
#

# --- Copied from the BB init script ---

PATH=$PATH:/bin:/usr/bin		# FOR su
PP_SERVICE_HOME=/opt/open-english/pp-service
PP_SERVICE_USER=oe

case "$1" in
start)
    su $PP_SERVICE_USER -c $PP_SERVICE_HOME/pp-service-run.sh
    echo "Starting PP_SERVICE Server."
    ;;
stop)
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-stop.sh"
    echo "Stopping PP_SERVICE Server."
    ;;
restart)
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-stop.sh"
    echo "Stopping PP_SERVICE Server."
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-run.sh"
    echo "Restarting PP_SERVICE Server."
    ;;
force-reload)
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-stop.sh"
    echo "Stopping PP_SERVICE Server."
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-run.sh"
    echo "Restarting PP_SERVICE Server."
    echo "Force reload of PP_SERVICE Server."
    ;;
status)
    echo "Status of PP_SERVICE Server..."
    su $PP_SERVICE_USER -c "cd $PP_SERVICE_HOME;$PP_SERVICE_HOME/pp-service-status.sh"
    ;;
*)
    echo "Usage: $0 {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
