# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :oe_system_three_reference do |oe_system_three_reference|
    oe_system_three_reference.vm.provision :shell, path: "vminit.sh"
    oe_system_three_reference.vm.network :forwarded_port, host: 8700, guest: 80
    oe_system_three_reference.vm.network :forwarded_port, host: 8790, guest: 8090
    oe_system_three_reference.vm.network :forwarded_port, host: 8743, guest: 443
    # port for remote debugging with IntelliJ or other IDE
    oe_system_three_reference.vm.network :forwarded_port, host: 8705, guest: 5005
    # activemq monitoring port
    oe_system_three_reference.vm.network :forwarded_port, host: 8761, guest: 8161
    oe_system_three_reference.vm.box = "https://s3.amazonaws.com/dev.virtual-machines/lp2-base.box"
    # map htdocs root to our bin dir
    oe_system_three_reference.vm.synced_folder "../target/", "/home/vagrant/target"
    oe_system_three_reference.vm.synced_folder "~", "/home/vagrant/user-home"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

end
