# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :oe_hr_portal_service do |oe_hr_portal_service|
    oe_hr_portal_service.vm.provision :shell, path: "vminit.sh"
    oe_hr_portal_service.vm.network :forwarded_port, host: 6900, guest: 80
    oe_hr_portal_service.vm.network :forwarded_port, host: 6990, guest: 8090
    oe_hr_portal_service.vm.network :forwarded_port, host: 6943, guest: 443
    # port for remote debugging with IntelliJ or other IDE
    oe_hr_portal_service.vm.network :forwarded_port, host: 6905, guest: 5005
    # activemq monitoring port
    oe_hr_portal_service.vm.network :forwarded_port, host: 6961, guest: 8161
    oe_hr_portal_service.vm.box = "https://s3.amazonaws.com/dev.virtual-machines/lp2-base.box"
    # map htdocs root to our bin dir
    oe_hr_portal_service.vm.synced_folder "../target/", "/home/vagrant/target"
    oe_hr_portal_service.vm.synced_folder "~", "/home/vagrant/user-home"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

end
